We recommend that you think again before deactivating your account. If you are not happy with the app or have experienced some other issue due to the app, you can contact us at: <a href="mailto:team@teamonapp.com">team@teamonapp.com</a> and we will resolve the issue promptly.

If you want to just disable notifications from the app, you can go to More > Notifications settings and disable all notifications. 

Deactivating account will permanently disable your ability to sign-in to the app and view any games you may have organized or participated in. 

Do you still want to proceed with the deactivation?  If No, just go back by pressing back from top left. If yes, please press the button below.